# Generated by Django 6.0.4 on 2026-04-15 18:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('apply_link', models.URLField(max_length=700, unique=True)),
                ('posted_date_raw', models.CharField(blank=True, max_length=100, null=True)),
                ('parsed_date', models.DateField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-parsed_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ScraperLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=20)),
                ('message', models.TextField()),
                ('jobs_added', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Scraper Log',
                'verbose_name_plural': 'Scraper Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
